In [1]:
# Text Representation - Bag Of Words (BOW)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts() # this shows how many spam and ham (regular emails) emails we have

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
# Create a new column 'spam' where spam = 1 and ham = 0
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [6]:
df.shape

(5572, 3)

In [7]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
# Train test split

In [9]:
from sklearn.model_selection import train_test_split
# our X is the Message column and y is the spam column(1 for spam, 0 for ham)
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
X_train.shape # shape of 80% of messages.

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train) # pandas Series

pandas.core.series.Series

In [ ]:
X_train[:4] # first 4 messages in the training set
# 4227 is first message index in training set (these are random samples, thats why they are not in order)

4227    Ok thats cool. Its , just off either raglan rd...
2352    Download as many ringtones as u like no restri...
1999    Well, I have to leave for my class babe ... Yo...
4660    I cant pick the phone right now. Pls send a me...
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4] # first 4 labels in the training set
# 1 means spam, 0 means ham

4227    0
2352    1
1999    0
4660    0
Name: spam, dtype: int64

In [16]:
type(X_train.values)

numpy.ndarray

In [17]:
# Create bag of words representation using CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values) # when we use fit_transform, it learns the vocabulary and creates the bag of words model
X_train_cv # this is a sparse matrix representation of the bag of words model

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59107 stored elements and shape (4457, 7740)>

In [ ]:
X_train_cv.toarray()[:2][0] # first message array representation

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
X_train_cv.shape # (4457, 7740) -> 4457 messages and 7740 unique words in the vocabulary

(4457, 7740)

In [ ]:
v.get_feature_names_out()[1771] # checking which word is at index 1771 in the vocabulary

'cheating'

In [ ]:
v.vocabulary_ # this shows the mapping of words to their index in the vocabulary in the bag of words model

{'ok': 4909,
 'thats': 6812,
 'cool': 2025,
 'its': 3767,
 'just': 3874,
 'off': 4888,
 'either': 2560,
 'raglan': 5540,
 'rd': 5577,
 'or': 4961,
 'edward': 2543,
 'behind': 1331,
 'the': 6813,
 'cricket': 2097,
 'ground': 3260,
 'gimme': 3144,
 'ring': 5779,
 'when': 7475,
 'ur': 7199,
 'closeby': 1868,
 'see': 5980,
 'you': 7703,
 'tuesday': 7071,
 'download': 2437,
 'as': 1102,
 'many': 4350,
 'ringtones': 5784,
 'like': 4108,
 'no': 4789,
 'restrictions': 5743,
 '1000s': 264,
 'choose': 1822,
 'can': 1652,
 'even': 2667,
 'send': 6005,
 'yr': 7717,
 'buddys': 1567,
 'txt': 7093,
 'sir': 6181,
 'to': 6931,
 '80082': 644,
 'well': 7450,
 'have': 3364,
 'leave': 4056,
 'for': 2950,
 'my': 4666,
 'class': 1851,
 'babe': 1213,
 'never': 4751,
 'came': 1649,
 'back': 1220,
 'me': 4406,
 'hope': 3490,
 'nice': 4765,
 'sleep': 6215,
 'love': 4227,
 'cant': 1664,
 'pick': 5195,
 'phone': 5181,
 'right': 5773,
 'now': 4838,
 'pls': 5246,
 'message': 4458,
 'asked': 1114,
 'money': 4570,
 'how': 3522,
 'far': 2785,
 'yes': 7686,
 'he': 3374,
 'is': 3748,
 'really': 5599,
 'great': 3244,
 'bhaji': 1363,
 'told': 6948,
 'kallis': 3887,
 'best': 1350,
 'cricketer': 2098,
 'after': 863,
 'sachin': 5859,
 'in': 3647,
 'world': 7593,
 'very': 7271,
 'tough': 6997,
 'get': 3126,
 'out': 4997,
 'rightio': 5774,
 '11': 274,
 '48': 515,
 'it': 3760,
 'then': 6826,
 'arent': 1067,
 'we': 7414,
 'all': 921,
 'up': 7181,
 'bright': 1527,
 'and': 972,
 'early': 2512,
 'this': 6855,
 'morning': 4589,
 'am': 946,
 'taking': 6689,
 'italian': 3761,
 'food': 2941,
 'about': 764,
 'pretty': 5389,
 'dress': 2457,
 'with': 7541,
 'panties': 5060,
 'here': 3417,
 'new': 4754,
 'address': 823,
 'apples': 1037,
 'pairs': 5049,
 'that': 6810,
 'malarky': 4331,
 'hey': 3425,
 'gorgeous': 3204,
 'man': 4335,
 'work': 7586,
 'mobile': 4543,
 'number': 4853,
 'good': 3191,
 'one': 4928,
 'squishy': 6419,
 'mwahs': 4665,
 'are': 1064,
 'having': 3369,
 'semester': 6001,
 'do': 2390,
 'wish': 7533,
 'made': 4305,
 'greatness': 3246,
 'sorry': 6329,
 'll': 4157,
 'call': 1631,
 'later': 4022,
 'total': 6992,
 'video': 7281,
 'converter': 2016,
 'free': 2992,
 'type': 7106,
 'google': 3202,
 'search': 5963,
 'sometimes': 6305,
 'slow': 6233,
 'gentle': 3118,
 'sonetimes': 6313,
 'rough': 5817,
 'hard': 3345,
 'alrite': 936,
 'urgh': 7205,
 'coach': 1889,
 'hot': 3509,
 'smells': 6246,
 'of': 4886,
 'chip': 1815,
 'fat': 2793,
 'thanks': 6803,
 'again': 869,
 'especially': 2652,
 'duvet': 2503,
 'not': 4825,
 'predictive': 5366,
 'text': 6786,
 'word': 7584,
 'awarded': 1193,
 'city': 1840,
 'break': 1511,
 'could': 2051,
 'win': 7514,
 '200': 354,
 'summer': 6588,
 'shopping': 6109,
 'spree': 6410,
 'every': 2673,
 'wk': 7549,
 'store': 6499,
 '88039': 703,
 'skilgme': 6199,
 'tscs087147403231winawk': 7064,
 'age16': 873,
 '50perwksub': 549,
 'oh': 4905,
 'fun': 3053,
 'haha': 3307,
 'take': 6685,
 'care': 1677,
 'there': 6832,
 'be': 1297,
 'minor': 4498,
 'shindig': 6086,
 'at': 1137,
 'place': 5222,
 'tonight': 6967,
 'interested': 3714,
 've': 7259,
 'got': 3208,
 'ten': 6763,
 'bucks': 1564,
 'jay': 3801,
 'being': 1333,
 'noncomittal': 4805,
 'yesterday': 7688,
 'been': 1317,
 'wonderful': 7573,
 'enjoyed': 2607,
 'burial': 1586,
 'mojibiola': 4560,
 'why': 7498,
 'so': 6281,
 'pansy': 5058,
 'living': 4154,
 'jungle': 3870,
 'two': 7092,
 'years': 7676,
 'driving': 2467,
 'should': 6121,
 'more': 4585,
 'worried': 7596,
 'stupid': 6539,
 'auto': 1171,
 'correct': 2036,
 'on': 4924,
 'guess': 3278,
 'useless': 7219,
 'calling': 1643,
 'something': 6303,
 'important': 3636,
 'still': 6478,
 'grinder': 3253,
 'did': 2320,
 'slice': 6222,
 'breadstick': 1510,
 'lol': 4183,
 'sing': 6172,
 'hu': 3539,
 'think': 6847,
 'also': 937,
 'find': 2863,
 'someone': 6299,
 'female': 2823,
 'know': 3951,
 'preferably': 5368,
 'citizen': 1839,
 'smart': 6241,
 'help': 3406,
 'navigate': 4710,
 'through': 6876,
 'things': 6846,
 'choosing': 1823,
 'plan': 5226,
 'require': 5716,
 'guidance': 3283,
 'doubt': 2433,
 'ask': 1112,
 'girls': 3150,
 'plans': 5232,
 'yet': 7689,
 'what': 7469,
 'doing': 2408,
 'makes': 4326,
 'most': 4592,
 'happy': 3344,
 'sent': 6015,
 'an': 969,
 'email': 2576,
 'log': 4174,
 'into': 3722,
 'usc': 7215,
 'payment': 5117,
 'portal': 5305,
 'another': 992,
 'explain': 2730,
 'home': 3474,
 'weekend': 7437,
 'will': 7512,
 'go': 3170,
 'walmart': 7371,
 'stay': 6455,
 'din': 2343,
 'tell': 6752,
 'jus': 3873,
 '420': 493,
 'skint': 6204,
 'too': 6972,
 'but': 1598,
 'fancied': 2778,
 'few': 2828,
 'bevies': 1358,
 'waz': 7411,
 'gona': 3186,
 'meet': 4425,
 'othrs': 4989,
 'spoon': 6401,
 'jst': 3860,
 'bin': 1379,
 'watchng': 7400,
 'planet': 5228,
 'earth': 2516,
 'sofa': 6285,
 'comfey': 1929,
 'if': 3606,
 'dont': 2417,
 'make': 4325,
 'hav': 3361,
 'gd': 3106,
 'night': 4772,
 'watever': 7402,
 'relation': 5665,
 'built': 1575,
 'dis': 2358,
 'only': 4934,
 'thing': 6845,
 'which': 7484,
 'remains': 5676,
 'atlast': 1141,
 'iz': 3775,
 'lonlines': 4192,
 'lotz': 4220,
 'lot': 4213,
 'memories': 4443,
 'feeling': 2815,
 'north': 4819,
 'carolina': 1688,
 'texas': 6785,
 'atm': 1143,
 'would': 7607,
 'gre': 3243,
 'site': 6187,
 'pay': 5113,
 'test': 6781,
 'results': 5747,
 'meant': 4414,
 'calculation': 1627,
 'same': 5887,
 'lt': 4251,
 'gt': 3268,
 'units': 7161,
 'school': 5934,
 'expensive': 2724,
 'started': 6445,
 'practicing': 5347,
 'your': 7707,
 'accent': 780,
 'because': 1306,
 'decided': 2222,
 '4years': 542,
 'dental': 2260,
 'nmde': 4788,
 'exam': 2700,
 'where': 7479,
 'yuou': 7725,
 'working': 7590,
 'getting': 3133,
 'pc': 5121,
 'mom': 4563,
 'spot': 6406,
 'need': 4724,
 'maaaan': 4291,
 'missing': 4515,
 'escape': 2649,
 'theatre': 6816,
 'going': 3181,
 'watch': 7397,
 'kavalan': 3897,
 'minutes': 4503,
 'lar': 4011,
 'testing': 6782,
 'card': 1674,
 'dunno': 2499,
 'network': 4746,
 'thk': 6856,
 'waiting': 7356,
 'sis': 6183,
 'finish': 2869,
 'bathing': 1275,
 'bathe': 1274,
 'dun': 2497,
 'disturb': 2377,
 'liao': 4088,
 'cleaning': 1855,
 'room': 5809,
 'login': 4177,
 'anything': 1014,
 'let': 4082,
 'called': 1637,
 'falling': 2771,
 'bcoz': 1292,
 'force': 2951,
 'yourself': 7712,
 'fall': 2769,
 'smeone': 6247,
 'hold': 3465,
 'bslvyl': 1556,
 'book': 1446,
 'lesson': 4080,
 'msg': 4616,
 'sth': 6474,
 'specs': 6368,
 'membership': 4441,
 'px3748': 5505,
 'havent': 3366,
 'waitin': 7355,
 'usual': 7226,
 'come': 1926,
 'sch': 5932,
 'oredi': 4971,
 'spjanuary': 6387,
 'male': 4332,
 'sale': 5876,
 'gay': 3097,
 'chat': 1766,
 'cheaper': 1770,
 '08709222922': 92,
 'national': 4702,
 'rate': 5564,
 'from': 3030,
 '5p': 566,
 'min': 4484,
 'cheap': 1769,
 '8p': 721,
 'peak': 5127,
 'stop': 6490,
 'texts': 6796,
 '08712460324': 111,
 '10p': 271,
 'congratulations': 1986,
 'won': 7569,
 're': 5579,
 'winner': 7524,
 'our': 4994,
 'august': 1162,
 '1000': 262,
 'prize': 5410,
 'draw': 2451,
 '09066660100': 243,
 'code': 1898,
 '2309': 370,
 'fine': 2866,
 'imma': 3630,
 'drink': 2459,
 'somethin': 6302,
 'want': 7378,
 'hello': 3404,
 'news': 4758,
 'job': 3833,
 'they': 6840,
 'making': 4329,
 'wait': 7353,
 'fifth': 2840,
 'week': 7435,
 'yeah': 7674,
 'im': 3621,
 'some': 6295,
 'woozles': 7582,
 'weasels': 7421,
 'exeter': 2712,
 'dear': 2212,
 'reaching': 5583,
 'receive': 5617,
 'has': 3355,
 'ended': 2592,
 'day': 2200,
 'special': 6362,
 'way': 7409,
 'may': 4397,
 'smile': 6249,
 'sunny': 6597,
 'rays': 5572,
 'leaves': 4057,
 'worries': 7597,
 'blue': 1424,
 'bay': 1280,
 'gud': 3274,
 'mrng': 4613,
 'pdate_now': 5123,
 'double': 2429,
 'mins': 4499,
 'txts': 7101,
 'orange': 4964,
 'tariffs': 6705,
 'latest': 4023,
 'motorola': 4598,
 'sonyericsson': 6317,
 'nokia': 4799,
 'bluetooth': 1425,
 'mobileupd8': 4546,
 '08000839402': 46,
 'call2optout': 1633,
 'yhl': 7692,
 'wanna': 7376,
 'set': 6030,
 '09096102316': 251,
 'cum': 2132,
 '2moro': 407,
 'luv': 4269,
 'jane': 3792,
 'xx': 7650,
 'calls': 1645,
 'minmoremobsemspobox45po139wa': 4496,
 'fair': 2763,
 'enough': 2612,
 'brand': 1502,
 'music': 4654,
 'service': 6027,
 'live': 4149,
 'player': 5236,
 'arrive': 1092,
 'shortly': 6117,
 'install': 3702,
 'browse': 1552,
 'content': 2003,
 'top': 6981,
 'artists': 1097,
 'sweater': 6645,
 'fr': 2981,
 'mango': 4347,
 'size': 6195,
 'already': 934,
 'irritating': 3746,
 'bird': 1381,
 'any': 1005,
 'purchases': 5491,
 'fantasy': 2784,
 'football': 2945,
 'tv': 7083,
 'sky': 6207,
 'gamestar': 3080,
 'active': 810,
 'play': 5234,
 '250k': 379,
 'dream': 2454,
 'team': 6734,
 'scoring': 5942,
 'starts': 6447,
 'saturday': 5910,
 'register': 5657,
 'opt': 4955,
 '88088': 705,
 'wishing': 7537,
 'family': 2775,
 'merry': 4455,
 'mas': 4369,
 'year': 7675,
 'advance': 842,
 'networking': 4747,
 'person': 5155,
 'who': 7490,
 'sms': 6261,
 'survey': 6628,
 'wan': 7373,
 'lei': 4068,
 'outside': 5008,
 'wun': 7635,
 'neva': 4749,
 'mind': 4487,
 'training': 7009,
 'by': 1614,
 'put': 5500,
 'skip': 6205,
 'front': 3033,
 'house': 3518,
 'pull': 5481,
 'before': 1323,
 'better': 1355,
 'wake': 7357,
 'lor': 4205,
 'must': 4657,
 'huh': 3548,
 'yoga': 7699,
 'basic': 1265,
 'sunday': 6594,
 'antibiotic': 1004,
 'used': 7217,
 'chest': 1789,
 'abdomen': 754,
 'gynae': 3298,
 'infections': 3675,
 'bone': 1441,
 'damn': 2172,
 'christmas': 1831,
 'keep': 3903,
 'mp3': 4609,
 'doesnt': 2401,
 '0776xxxxxxx': 27,
 'invited': 3731,
 'xchat': 7643,
 'final': 2859,
 'attempt': 1147,
 'contact': 1999,
 '86688': 692,
 '150p': 309,
 'msgrcvdhg': 4620,
 'suite342': 6580,
 '2lands': 405,
 'row': 5821,
 'w1j6hl': 7336,
 'ldn': 4041,
 '18yrs': 330,
 'lifted': 4102,
 'hopes': 3495,
 'offer': 4892,
 'end': 2591,
 'month': 4579,
 'approaches': 1046,
 'hurts': 3567,
 'studying': 6533,
 'anyways': 1018,
 'gr8': 3220,
 'hmmm': 3455,
 'sure': 6618,
 'time': 6902,
 'hop': 3489,
 'ard': 1063,
 'ya': 7661,
 'abt': 772,
 'muz': 4663,
 'discuss': 2368,
 'celebrate': 1724,
 'else': 2573,
 'had': 3304,
 'dinner': 2347,
 'town': 7000,
 'exciting': 2705,
 'adult': 840,
 'singles': 6176,
 'uk': 7120,
 'check': 1773,
 'videos': 7284,
 'shsex': 6140,
 'netun': 4744,
 'fgkslpopw': 2834,
 'fgkslpo': 2833,
 '500': 544,
 'cd': 1718,
 'gift': 3140,
 'vouchers': 7326,
 'entry': 2624,
 '100': 261,
 'weekly': 7439,
 '87066': 694,
 'tncs': 6930,
 'www': 7636,
 'ldew': 4040,
 'com1win150ppmx3age16': 1921,
 'girl': 3147,
 'propose': 5452,
 'today': 6938,
 'seing': 5990,
 'bloody': 1419,
 'funky': 3058,
 'shit': 6094,
 'fucking': 3042,
 'face': 2749,
 'asssssholeeee': 1126,
 'wont': 7576,
 'first': 2882,
 'odi': 4885,
 'yellow': 7680,
 'travel': 7024,
 'gone': 3187,
 'eng': 2600,
 'rocking': 5798,
 'ashes': 1106,
 'bout': 1471,
 'last': 4017,
 'nite': 4784,
 'wasn': 7392,
 'fault': 2798,
 'was': 7390,
 'spouse': 6408,
 'pmt': 5254,
 'sumthin': 6591,
 '4give': 527,
 'shldxxxx': 6101,
 'thx': 6888,
 'months': 4581,
 'printer': 5403,
 'mean': 4409,
 'groovy': 3258,
 'wine': 7521,
 'groovying': 3259,
 'quite': 5525,
 'bit': 1389,
 'ex': 2697,
 'eat': 2523,
 'smth': 6266,
 'feel': 2813,
 'guilty': 3287,
 'noe': 4793,
 'da': 2163,
 'aft': 862,
 'wat': 7396,
 'hella': 3403,
 'gas': 3092,
 'grand': 3229,
 'nature': 4705,
 'adventure': 843,
 'galileo': 3075,
 'little': 4148,
 'watching': 7399,
 'honey': 3478,
 'much': 4632,
 'sell': 5997,
 'predicte': 5363,
 'nigeria': 4771,
 'times': 6903,
 'reply': 5707,
 'monday': 4568,
 'whats': 7471,
 'sleeping': 6217,
 'bringing': 1532,
 'dobby': 2392,
 'block': 1410,
 'breaker': 1512,
 'comes': 1928,
 'deluxe': 2255,
 'format': 2967,
 'features': 2808,
 'graphics': 3235,
 'buy': 1602,
 'replying': 5708,
 'bbdeluxe': 1284,
 'challenge': 1739,
 'haven': 3365,
 'eh': 2555,
 'life': 4097,
 'alle': 925,
 'mone': 4569,
 'eppolum': 2630,
 'oru': 4982,
 'pole': 5280,
 'allalo': 923,
 'skateboarding': 6198,
 'despite': 2286,
 'fact': 2752,
 'gets': 3129,
 'thrown': 6880,
 'winds': 7519,
 'bandages': 1240,
 'over': 5015,
 'his': 3442,
 'arms': 1084,
 'five': 2886,
 'ain': 892,
 'answerin': 997,
 'actually': 814,
 'reasonable': 5605,
 'hour': 3515,
 'sleepy': 6220,
 'everything': 2682,
 'frnd': 3021,
 'juz': 3879,
 'merely': 4453,
 'relationship': 5666,
 'silent': 6159,
 'promise': 5439,
 'says': 5923,
 'wherevr': 7482,
 'whenevr': 7477,
 'forevr': 2956,
 'gudnyt': 3277,
 'relatives': 5667,
 'de': 2206,
 'always': 944,
 'available': 1176,
 'hack': 3303,
 'backdoor': 1221,
 '121': 288,
 'rooms': 5813,
 'fraction': 2982,
 'cost': 2042,
 'neo69': 4737,
 '09050280520': 175,
 'subscribe': 6552,
 '25p': 380,
 'pm': 5253,
 'dps': 2444,
 'bcm': 1288,
 'box': 1475,
 '8027': 649,
 'wc1n3xx': 7413,
 'hi': 3429,
 'both': 1465,
 'said': 5871,
 'hasn': 3357,
 'seen': 5986,
 'him': 3437,
 'down': 2436,
 'gently': 3120,
 'please': 5240,
 'rs': 5829,
 'shelf': 6074,
 'egg': 2552,
 'prasanth': 5354,
 'ettans': 2658,
 'mother': 4594,
 'passed': 5094,
 'away': 1194,
 'pray': 5357,
 'her': 3416,
 'accidentally': 787,
 'left': 4062,
 'didn': 2322,
 'til': 6899,
 'she': 6070,
 'messages': 4460,
 'gosh': 3205,
 'pain': 5045,
 'spose': 6405,
 'painting': 5048,
 'wall': 7367,
 'mm': 4531,
 'itself': 3768,
 'shall': 6057,
 'princess': 5401,
 'command': 1933,
 'thnk': 6859,
 'wrong': 7623,
 'between': 1357,
 'us': 7213,
 'urgent': 7203,
 '2000': 355,
 'bonus': 1443,
 'caller': 1638,
 '03': 13,
 'try': 7057,
 'landline': 4000,
 '09064019788': 221,
 'box42wr29c': 1486,
 '150ppm': 313,
 'india': 3667,
 'series': 6022,
 'south': 6345,
 'african': 861,
 'soil': 6288,
 'might': 4476,
 'rock': 5797,
 'wen': 7453,
 'friendship': 3017,
 'poem': 5273,
 'near': 4716,
 'hear': 3384,
 'fear': 2806,
 'cheer': 1779,
 'tear': 6736,
 'ni8': 4763,
 '08715205273': 129,
 'yup': 7726,
 'surfing': 6620,
 'lazy': 4037,
 'mode': 4553,
 'officially': 4898,
 'philosophical': 5177,
 'hole': 3468,
 'ready': 5590,
 'saved': 5915,
 'waqt': 7383,
 'se': 5961,
 'pehle': 5131,
 'naseeb': 4697,
 'zyada': 7737,
 'kisi': 3940,
 'ko': 3956,
 'kuch': 3969,
 'nahi': 4681,
 'milta': 4483,
 'zindgi': 7734,
 'wo': 7561,
 'jo': 3831,
 'hum': 3551,
 'sochte': 6283,
 'hai': 3309,
 'ham': 3318,
 'jeetey': 3809,
 'lunch': 4264,
 'maggi': 4312,
 'mee': 4424,
 '26th': 383,
 'july': 3867,
 'issue': 3757,
 'weigh': 7441,
 'breathe': 1517,
 'easier': 2517,
 'regret': 5660,
 'amazing': 948,
 'rearrange': 5603,
 'these': 6834,
 'letters': 4085,
 'gives': 3155,
 'meaning': 4410,
 'dormitory': 2425,
 'dirty': 2357,
 'astronomer': 1134,
 'moon': 4583,
 'starer': 6439,
 'eyes': 2744,
 'election': 2567,
 'lies': 4096,
 'lets': 4083,
 'recount': 5633,
 'law': 4033,
 'woman': 7566,
 'hitler': 3445,
 'eleven': 2570,
 'plus': 5250,
 'twelve': 7085,
 'those': 6863,
 'cutest': 2155,
 'alex': 913,
 'knows': 3954,
 'guy': 3292,
 'sells': 5999,
 'mids': 4475,
 'tampa': 6700,
 'don': 2413,
 'old': 4917,
 'airport': 896,
 'road': 5792,
 '630': 584,
 'pple': 5339,
 'whole': 7492,
 'car': 1673,
 'appreciated': 1045,
 'dad': 2166,
 'map': 4351,
 'reading': 5589,
 'semi': 6002,
 'argument': 1075,
 'apart': 1021,
 'next': 4761,
 'give': 3153,
 'full': 3050,
 'gist': 3151,
 'private': 5408,
 '2003': 356,
 'account': 793,
 'statement': 6452,
 '07808': 31,
 'xxxxxx': 7656,
 'shows': 6136,
 '800': 640,
 'un': 7130,
 'redeemed': 5639,
 'points': 5276,
 '08719899217': 160,
 'identifier': 3601,
 '41685': 492,
 'expires': 2728,
 '07': 17,
 '04': 14,
 'movie': 4605,
 'shoot': 6106,
 'big': 1368,
 'loads': 4162,
 'connection': 1989,
 'bw': 1610,
 'means': 4413,
 'people': 5138,
 'them': 6822,
 'friends': 3015,
 'ge': 3108,
 'machan': 4296,
 'once': 4927,
 'elaine': 2563,
 'meeting': 4427,
 'confirmed': 1980,
 'trying': 7059,
 'weekends': 7438,
 '900': 725,
 'guaranteed': 3272,
 '09061701939': 201,
 'claim': 1842,
 's89': 5856,
 'valid': 7242,
 '12hrs': 292,
 'sdryb8i': 5960,
 'sunshine': 6600,
 'hols': 3472,
 'med': 4420,
 'holiday': 3469,
 'stamped': 6431,
 'self': 5994,
 'envelope': 2628,
 'drinks': 2462,
 'po': 5255,
 '113': 276,
 'bray': 1507,
 'wicklow': 7501,
 'eire': 2559,
 'quiz': 5528,
 'unsub': 7176,
 'telugu': 6758,
 'pa': 5034,
 'aha': 882,
 'were': 7459,
 'gonna': 3189,
 'tacos': 6678,
 'tirupur': 6912,
 'gibbs': 3138,
 ...}

In [ ]:
X_train_np = X_train_cv.toarray() # converting sparse matrix to a numpy array
X_train_np[0] # first message array representation

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
np.where(X_train_np[0]!=0) # in the first message, the indices where the word count is not zero.

(array([1331, 1868, 2025, 2097, 2543, 2560, 3144, 3260, 3767, 3874, 4888,
        4909, 4961, 5540, 5577, 5779, 5980, 6812, 6813, 7071, 7199, 7475,
        7703], dtype=int64),)

In [ ]:
X_train[:4] # first 4 messages in the training set

4227    Ok thats cool. Its , just off either raglan rd...
2352    Download as many ringtones as u like no restri...
1999    Well, I have to leave for my class babe ... Yo...
4660    I cant pick the phone right now. Pls send a me...
Name: Message, dtype: object

In [ ]:
X_train[:4][4227] # first message in the training set

'Ok thats cool. Its , just off either raglan rd or edward rd. Behind the cricket ground. Gimme ring when ur closeby see you tuesday.'

In [ ]:
X_train_np[0][1771] # checking the count of the word at index 1771 in the first message

0

In [31]:
# Train the naive bayes model

In [ ]:
# training the above bag of words model (X_train_cv) with Multinomial Naive Bayes again.
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [33]:
# we have bag of words model (X_train_cv) for training data, now we need to create bag of 
# words model for test data (X_test_cv).
X_test_cv = v.transform(X_test) # we only use transform here because we don't want to learn a new vocabulary, we want to use the existing one.

In [34]:
# Evaluate Performance

In [35]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv) # passing the test bag of words model (X_test_cv) to the trained model to get predictions

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.99      0.94      0.96       145

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails) # creating bag of words model for the new emails using the existing vocabulary
model.predict(emails_count) # passing the new emails bag of words model to the trained model (we again trained it using NB algorithm above) to get predictions

array([0, 1], dtype=int64)

In [37]:
# Train the model using sklearn pipeline and reduce number of lines of code

In [ ]:
from sklearn.pipeline import Pipeline
# here we are creating a pipeline with two steps: first step is CountVectorizer to create bag of words model, 
# second step is MultinomialNB to train the model
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])
# in return we got a clf object with bag of words model again trained on NB algorithm.

In [40]:
X_train

4227    Ok thats cool. Its , just off either raglan rd...
2352    Download as many ringtones as u like no restri...
1999    Well, I have to leave for my class babe ... Yo...
4660    I cant pick the phone right now. Pls send a me...
283                         Ok. I asked for money how far
                              ...
1222                               Prakesh is there know.
3922    Do 1 thing! Change that sentence into: "Becaus...
3560    URGENT! We are trying to contact U Todays draw...
2145    FreeMsg: Hey - I'm Buffy. 25 and love to satis...
3076    Take us out shopping and Mark will distract Is...
Name: Message, Length: 4457, dtype: object

In [41]:
y_train

4227    0
2352    1
1999    0
4660    0
283     0
       ..
1222    0
3922    0
3560    1
2145    1
3076    0
Name: spam, Length: 4457, dtype: int64

In [ ]:
clf.fit(X_train, y_train) # training the pipeline model with training data

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       976
           1       0.98      0.93      0.95       139

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115